# Generated by Django 4.2.3 on 2023-07-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pizzacategory_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='compaund',
            field=models.CharField(default=0, max_length=150, verbose_name='Склад піци'),
        ),
    ]
