# Generated by Django 4.2.3 on 2023-07-09 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_salad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('drink_name', models.CharField(max_length=100, verbose_name='Назва напою')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('weight', models.IntegerField(verbose_name='Вага')),
                ('images', models.ImageField(upload_to='drink', verbose_name='Фото напою')),
            ],
            options={
                'verbose_name': 'Напій',
                'verbose_name_plural': 'Напої',
            },
        ),
        migrations.AlterField(
            model_name='pizza',
            name='compaund',
            field=models.CharField(max_length=150, verbose_name='Склад піци'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='images',
            field=models.ImageField(upload_to='salad', verbose_name='Фото салату'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='weight',
            field=models.IntegerField(verbose_name='Вага'),
        ),
    ]
