# Generated by Django 4.2.3 on 2023-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpeg', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
