# Generated by Django 4.2.3 on 2023-07-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderitems_drink_orderitems_salad_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='salad',
        ),
    ]
