# Generated by Django 4.2.3 on 2023-07-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_orderitems_drink_remove_orderitems_salad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pizza'),
        ),
    ]
