# Generated by Django 4.2.3 on 2023-07-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderitems_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='drink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.drink'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='salad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.salad'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='pizza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.pizza'),
        ),
    ]
