# Generated by Django 4.2.3 on 2023-07-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orderitems_drink_orderitems_salad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='pizza',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='pizza',
            field=models.ManyToManyField(to='app.pizza'),
        ),
    ]
