# Generated by Django 4.2.3 on 2023-07-12 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_orderitems_pizza_orderitems_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDrink',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.drink')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drink', to='app.order')),
            ],
            options={
                'verbose_name': 'Замовлення Напою',
                'verbose_name_plural': 'Замовлення Напоїв',
            },
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pizza', to='app.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pizza')),
            ],
            options={
                'verbose_name': 'Замовлення Піци',
                'verbose_name_plural': 'Замовлення Піци',
            },
        ),
        migrations.CreateModel(
            name='OrderSalad',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_salad', to='app.order')),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salad')),
            ],
            options={
                'verbose_name': 'Замовлення Салату',
                'verbose_name_plural': 'Замовлення Салатів',
            },
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
