# Generated by Django 4.2.3 on 2023-07-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizza',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='ordersalad',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersalad',
            name='salad',
        ),
        migrations.DeleteModel(
            name='OrderDrink',
        ),
        migrations.DeleteModel(
            name='OrderPizza',
        ),
        migrations.DeleteModel(
            name='OrderSalad',
        ),
    ]
