# Generated by Django 4.2.3 on 2023-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Невідомо', max_length=40, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='apartment',
            field=models.IntegerField(default='Невідомо', verbose_name='Номер квартири'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Київ', max_length=12, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='UnknowUser', max_length=50, verbose_name="Ім'я та Прізвище"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0, verbose_name='Номер телефону'),
        ),
    ]
