# Generated by Django 4.2.3 on 2023-07-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_profile_address_alter_profile_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apartment',
            field=models.IntegerField(default='1111', verbose_name='Номер квартири'),
        ),
    ]
