# Generated by Django 4.2.3 on 2023-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order_item_count_order_total_price_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_30cm',
            field=models.IntegerField(default=0, verbose_name='Ціна - 30 см'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_40cm',
            field=models.IntegerField(default=0, verbose_name='Ціна - 40 см'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='weight_30cm',
            field=models.IntegerField(default=0, verbose_name='Вага - 30 см'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='weight_40cm',
            field=models.IntegerField(default=0, verbose_name='Вага - 40 см'),
        ),
    ]
