# Generated by Django 4.2.3 on 2023-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_pizza_price_pizza_price_30cm_pizza_price_40cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('30cm', '30 см'), ('40cm', '40 см')], default='30cm', max_length=10, verbose_name='Розмір піци'),
        ),
    ]
