# Generated by Django 4.2.3 on 2023-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price_30cm',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price_40cm',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='weight_30cm',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='weight_40cm',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Ціна'),
        ),
    ]
