# Generated by Django 4.2.3 on 2023-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_pizza_price_30cm_remove_pizza_price_40cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.IntegerField(default=100, verbose_name='Вага'),
        ),
    ]
